//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keyboard_typer_v1.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("keyboard_typer_v1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2
        ///1080
        ///&amp;c
        ///10-point
        ///10th
        ///11-point
        ///12-point
        ///16-point
        ///18-point
        ///1st
        ///2,4,5-t
        ///2,4-d
        ///20-point
        ///2D
        ///2nd
        ///30-30
        ///3D
        ///3-D
        ///3M
        ///3rd
        ///48-point
        ///4-D
        ///4GL
        ///4H
        ///4th
        ///5-point
        ///5-T
        ///5th
        ///6-point
        ///6th
        ///7-point
        ///7th
        ///8-point
        ///8th
        ///9-point
        ///9th
        ///a
        ///a&apos;
        ///a-
        ///A&amp;M
        ///A&amp;P
        ///A.
        ///A.A.A.
        ///A.B.
        ///A.B.A.
        ///A.C.
        ///A.D.
        ///A.D.C.
        ///A.F.
        ///A.F.A.M.
        ///A.G.
        ///A.H.
        ///A.I.
        ///A.I.A.
        ///A.I.D.
        ///A.L.
        ///A.L.P.
        ///A.M.
        ///A.M.A.
        ///A.M.D.G.
        ///A.N.
        ///a.p.
        ///a.r.
        ///A.R.C.S.
        ///A.U.
        ///A.U.C.
        ///A.V.
        ///a.w.
        ///A.W.O.L.
        ///A/C
        ///A/F
        ///A/O
        ///A/P
        ///A/V
        ///A1
        ///A-1
        ///A4
        ///A5
        ///AA
        ///AAA
        ///AAAA
        ///AAAAAA
        ///AAAL
        ///AAAS
        ///Aaberg
        ///Aachen
        ///AAE
        ///AAEE
        ///AAF
        ///AAG
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///AAII
        ///aal
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -де
        ///-ка
        ///-либо
        ///-нибудь
        ///-с
        ///-таки
        ///-то
        ///а
        ///а-конто
        ///а-ля
        ///а.л.
        ///аарона
        ///ааронов
        ///аб
        ///аба
        ///абажур
        ///абажура
        ///абажурам
        ///абажурами
        ///абажурах
        ///абажуре
        ///абажурная
        ///абажурного
        ///абажурное
        ///абажурной
        ///абажурном
        ///абажурному
        ///абажурною
        ///абажурную
        ///абажурные
        ///абажурный
        ///абажурным
        ///абажурными
        ///абажурных
        ///абажуров
        ///абажуродержателе
        ///абажуродержателей
        ///абажуродержателем
        ///абажуродержатели
        ///абажуродержатель
        ///абажуродержателю
        ///абажуродержателя
        ///абажуродержателям
        ///абажуродержателями
        ///абажуродержателях
        ///абажуром
        ///абажуру
        ///абажурчик
        ///абажурчика
        ///абажурчикам
        ///абажурчиками
        ///аба [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string russian {
            get {
                return ResourceManager.GetString("russian", resourceCulture);
            }
        }
    }
}
